# maxio_advanced_billing_formerly_chargify_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MaxioAdvancedBillingFormerlyChargifyApi
  # The vault that stores the payment profile with the provided vault_token.
  class PaymentProfileVaultEnum
    PAYMENT_PROFILE_VAULT_ENUM = [
      # TODO: Write general description for BOGUS
      BOGUS = 'bogus'.freeze,

      # TODO: Write general description for AUTHORIZENET
      AUTHORIZENET = 'authorizenet'.freeze,

      # TODO: Write general description for TRUST_COMMERCE
      TRUST_COMMERCE = 'trust_commerce'.freeze,

      # TODO: Write general description for PAYMENT_EXPRESS
      PAYMENT_EXPRESS = 'payment_express'.freeze,

      # TODO: Write general description for BEANSTREAM
      BEANSTREAM = 'beanstream'.freeze,

      # TODO: Write general description for BRAINTREE_BLUE
      BRAINTREE_BLUE = 'braintree_blue'.freeze,

      # TODO: Write general description for PAYPAL
      PAYPAL = 'paypal'.freeze,

      # TODO: Write general description for QUICKPAY
      QUICKPAY = 'quickpay'.freeze,

      # TODO: Write general description for EWAY
      EWAY = 'eway'.freeze,

      # TODO: Write general description for STRIPE
      STRIPE = 'stripe'.freeze,

      # TODO: Write general description for WIRECARD
      WIRECARD = 'wirecard'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_PROFILE_VAULT_ENUM.include?(value)
    end
  end
end
