# maxio_advanced_billing_formerly_chargify_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MaxioAdvancedBillingFormerlyChargifyApi
  # Resource Type.
  class ResourceTypeEnum
    RESOURCE_TYPE_ENUM = [
      # TODO: Write general description for SUBSCRIPTIONS
      SUBSCRIPTIONS = 'subscriptions'.freeze,

      # TODO: Write general description for CUSTOMERS
      CUSTOMERS = 'customers'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      RESOURCE_TYPE_ENUM.include?(value)
    end
  end
end
