# maxio_advanced_billing_formerly_chargify_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class WebhooksControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.webhooks
    @response_catcher = @controller.http_call_back
  end

  # ## Webhooks Intro
  #
  #The Webhooks API allows you to view a list of all webhooks and to selectively resend individual or groups of webhooks. Webhooks will be sent on endpoints specified by you. Endpoints can be added via API or Web UI. There is also an option to enable / disable webhooks via API request.
  #
  #We recommend that you review Chargify's webhook documentation located in our help site. The following resources will help guide you on how to use webhooks in Chargify, in addition to these webhook endpoints:
  #
  #+ [Adding/editing new webhooks](https://maxio-chargify.zendesk.com/hc/en-us/articles/5404448450317#configure-webhook-url)
  #+ [Webhooks introduction and delivery information](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405568068365#webhooks-introduction-0-0)
  #+ [Main webhook overview](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#webhooks-reference-0-0)
  #+ [Available webhooks and payloads](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#events)
  #
  ### List Webhooks for a Site
  #
  #This method allows you to fetch data about webhooks. You can pass query parameters if you want to filter webhooks.
  def test_list_webhooks
    # Parameters for the API call
    status = nil
    since_date = nil
    until_date = nil
    page = 1
    per_page = 20
    order = nil
    subscription = nil

    # Perform the API call through the SDK function
    result = @controller.list_webhooks(status: status, since_date: since_date,
                                       until_date: until_date, page: page,
                                       per_page: per_page, order: order,
                                       subscription: subscription)

    # Test response code
    assert_equal(201, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '[{"webhook":{"event":"statement_settled","id":141765032,"created_at":"2'\
      '016-11-08T16:22:26-05:00","last_error":"404 Resource Not Found (retry 5'\
      ' of 5)","last_error_at":"2016-11-08T16:43:54-05:00","accepted_at":null,'\
      '"last_sent_at":"2016-11-08T16:43:54-05:00","last_sent_url":"http://requ'\
      'estb.in/11u45x71","successful":false,"body":"id=141765032&event=stateme'\
      'nt_settled&payload[site][id]=31615&payload[site][subdomain]=general-goo'\
      'ds&payload[subscription][id]=15100141&payload[subscription][state]=acti'\
      've&payload[subscription][balance_in_cents]=0&payload[customer][id]=1458'\
      '5695&payload[customer][first_name]=Pookie&payload[customer][last_name]='\
      'Test&payload[customer][reference]=&payload[customer][organization]=&pay'\
      'load[customer][address]=&payload[customer][address_2]=&payload[customer'\
      '][city]=&payload[customer][state]=&payload[customer][zip]=&payload[cust'\
      'omer][country]=&payload[customer][email]=pookie999%40example.com&payloa'\
      'd[customer][phone]=&payload[statement][closed_at]=2016-11-08%2016%3A22%'\
      '3A20%20-0500&payload[statement][created_at]=2016-11-08%2016%3A22%3A18%2'\
      '0-0500&payload[statement][id]=80168049&payload[statement][opened_at]=20'\
      '16-11-07%2016%3A22%3A15%20-0500&payload[statement][settled_at]=2016-11-'\
      '08%2016%3A22%3A20%20-0500&payload[statement][subscription_id]=15100141&'\
      'payload[statement][updated_at]=2016-11-08%2016%3A22%3A20%20-0500&payloa'\
      'd[statement][starting_balance_in_cents]=0&payload[statement][ending_bal'\
      'ance_in_cents]=0&payload[statement][total_in_cents]=6400&payload[statem'\
      'ent][memo]=We%20thank%20you%20for%20your%20continued%20business!&payloa'\
      'd[statement][events][0][id]=346956565&payload[statement][events][0][key'\
      ']=renewal_success&payload[statement][events][0][message]=Successful%20r'\
      'enewal%20for%20Pookie%20Test\'s%20subscription%20to%20%2410%20Basic%20P'\
      'lan&payload[statement][events][1][id]=346956579&payload[statement][even'\
      'ts][1][key]=payment_success&payload[statement][events][1][message]=Succ'\
      'essful%20payment%20of%20%2464.00%20for%20Pookie%20Test\'s%20subscriptio'\
      'n%20to%20%2410%20Basic%20Plan&payload[statement][events][2][id]=3472993'\
      '59&payload[statement][events][2][key]=renewal_success&payload[statement'\
      '][events][2][message]=Successful%20renewal%20for%20Pookie%20Test\'s%20s'\
      'ubscription%20to%20%2410%20Basic%20Plan&payload[statement][transactions'\
      '][0][id]=161537343&payload[statement][transactions][0][subscription_id]'\
      '=15100141&payload[statement][transactions][0][type]=Charge&payload[stat'\
      'ement][transactions][0][kind]=baseline&payload[statement][transactions]'\
      '[0][transaction_type]=charge&payload[statement][transactions][0][succes'\
      's]=true&payload[statement][transactions][0][amount_in_cents]=1000&paylo'\
      'ad[statement][transactions][0][memo]=%2410%20Basic%20Plan%20(11%2F08%2F'\
      '2016%20-%2011%2F09%2F2016)&payload[statement][transactions][0][created_'\
      'at]=2016-11-08%2016%3A22%3A18%20-0500&payload[statement][transactions]['\
      '0][starting_balance_in_cents]=0&payload[statement][transactions][0][end'\
      'ing_balance_in_cents]=1000&payload[statement][transactions][0][gateway_'\
      'used]=&payload[statement][transactions][0][gateway_transaction_id]=&pay'\
      'load[statement][transactions][0][gateway_order_id]=&payload[statement]['\
      'transactions][0][payment_id]=161537369&payload[statement][transactions]'\
      '[0][product_id]=3792003&payload[statement][transactions][0][tax_id]=&pa'\
      'yload[statement][transactions][0][component_id]=&payload[statement][tra'\
      'nsactions][0][statement_id]=80168049&payload[statement][transactions][0'\
      '][customer_id]=14585695&payload[statement][transactions][0][original_am'\
      'ount_in_cents]=&payload[statement][transactions][0][discount_amount_in_'\
      'cents]=&payload[statement][transactions][0][taxable_amount_in_cents]=&p'\
      'ayload[statement][transactions][1][id]=161537344&payload[statement][tra'\
      'nsactions][1][subscription_id]=15100141&payload[statement][transactions'\
      '][1][type]=Charge&payload[statement][transactions][1][kind]=quantity_ba'\
      'sed_component&payload[statement][transactions][1][transaction_type]=cha'\
      'rge&payload[statement][transactions][1][success]=true&payload[statement'\
      '][transactions][1][amount_in_cents]=5400&payload[statement][transaction'\
      's][1][memo]=Timesheet%20Users%3A%2018%20Timesheet%20Users&payload[state'\
      'ment][transactions][1][created_at]=2016-11-08%2016%3A22%3A18%20-0500&pa'\
      'yload[statement][transactions][1][starting_balance_in_cents]=1000&paylo'\
      'ad[statement][transactions][1][ending_balance_in_cents]=6400&payload[st'\
      'atement][transactions][1][gateway_used]=&payload[statement][transaction'\
      's][1][gateway_transaction_id]=&payload[statement][transactions][1][gate'\
      'way_order_id]=&payload[statement][transactions][1][payment_id]=16153736'\
      '9&payload[statement][transactions][1][product_id]=3792003&payload[state'\
      'ment][transactions][1][tax_id]=&payload[statement][transactions][1][com'\
      'ponent_id]=277221&payload[statement][transactions][1][statement_id]=801'\
      '68049&payload[statement][transactions][1][customer_id]=14585695&payload'\
      '[statement][transactions][1][original_amount_in_cents]=&payload[stateme'\
      'nt][transactions][1][discount_amount_in_cents]=&payload[statement][tran'\
      'sactions][1][taxable_amount_in_cents]=&payload[statement][transactions]'\
      '[2][id]=161537369&payload[statement][transactions][2][subscription_id]='\
      '15100141&payload[statement][transactions][2][type]=Payment&payload[stat'\
      'ement][transactions][2][kind]=&payload[statement][transactions][2][tran'\
      'saction_type]=payment&payload[statement][transactions][2][success]=true'\
      '&payload[statement][transactions][2][amount_in_cents]=6400&payload[stat'\
      'ement][transactions][2][memo]=Pookie%20Test%20-%20%2410%20Basic%20Plan%'\
      '3A%20Renewal%20payment&payload[statement][transactions][2][created_at]='\
      '2016-11-08%2016%3A22%3A20%20-0500&payload[statement][transactions][2][s'\
      'tarting_balance_in_cents]=6400&payload[statement][transactions][2][endi'\
      'ng_balance_in_cents]=0&payload[statement][transactions][2][gateway_used'\
      ']=bogus&payload[statement][transactions][2][gateway_transaction_id]=534'\
      '33&payload[statement][transactions][2][gateway_order_id]=&payload[state'\
      'ment][transactions][2][payment_id]=&payload[statement][transactions][2]'\
      '[product_id]=3792003&payload[statement][transactions][2][tax_id]=&paylo'\
      'ad[statement][transactions][2][component_id]=&payload[statement][transa'\
      'ctions][2][statement_id]=80168049&payload[statement][transactions][2][c'\
      'ustomer_id]=14585695&payload[statement][transactions][2][card_number]=X'\
      'XXX-XXXX-XXXX-1&payload[statement][transactions][2][card_expiration]=10'\
      '%2F2020&payload[statement][transactions][2][card_type]=bogus&payload[st'\
      'atement][transactions][2][refunded_amount_in_cents]=0&payload[product]['\
      'id]=3792003&payload[product][name]=%2410%20Basic%20Plan&payload[product'\
      '_family][id]=527890&payload[product_family][name]=Acme%20Projects&paylo'\
      'ad[payment_profile][id]=10102821&payload[payment_profile][first_name]=P'\
      'ookie&payload[payment_profile][last_name]=Test&payload[payment_profile]'\
      '[billing_address]=&payload[payment_profile][billing_address_2]=&payload'\
      '[payment_profile][billing_city]=&payload[payment_profile][billing_count'\
      'ry]=&payload[payment_profile][billing_state]=&payload[payment_profile]['\
      'billing_zip]=&payload[event_id]=347299384","signature":"7c606ec4628ce75'\
      'ec46e284097ce163a","signature_hmac_sha_256":"40f25e83dd324508bb2149e3e5'\
      '25821922fb210535ebfbfa81e7ab951996b41d"}},{"webhook":{"event":"payment_'\
      'success","id":141765008,"created_at":"2016-11-08T16:22:25-05:00","last_'\
      'error":"404 Resource Not Found (retry 5 of 5)","last_error_at":"2016-11'\
      '-08T16:43:54-05:00","accepted_at":null,"last_sent_at":"2016-11-08T16:43'\
      ':54-05:00","last_sent_url":"http://requestb.in/11u45x71","successful":f'\
      'alse,"body":"id=141765008&event=payment_success&payload[site][id]=31615'\
      '&payload[site][subdomain]=general-goods&payload[subscription][id]=15100'\
      '141&payload[subscription][state]=active&payload[subscription][trial_sta'\
      'rted_at]=&payload[subscription][trial_ended_at]=&payload[subscription]['\
      'activated_at]=2016-11-04%2017%3A06%3A43%20-0400&payload[subscription][c'\
      'reated_at]=2016-11-04%2017%3A06%3A42%20-0400&payload[subscription][upda'\
      'ted_at]=2016-11-08%2016%3A22%3A22%20-0500&payload[subscription][expires'\
      '_at]=&payload[subscription][balance_in_cents]=0&payload[subscription][c'\
      'urrent_period_ends_at]=2016-11-09%2016%3A06%3A42%20-0500&payload[subscr'\
      'iption][next_assessment_at]=2016-11-09%2016%3A06%3A42%20-0500&payload[s'\
      'ubscription][canceled_at]=&payload[subscription][cancellation_message]='\
      '&payload[subscription][next_product_id]=&payload[subscription][cancel_a'\
      't_end_of_period]=false&payload[subscription][payment_collection_method]'\
      '=automatic&payload[subscription][snap_day]=&payload[subscription][cance'\
      'llation_method]=&payload[subscription][current_period_started_at]=2016-'\
      '11-08%2016%3A06%3A42%20-0500&payload[subscription][previous_state]=acti'\
      've&payload[subscription][signup_payment_id]=161034048&payload[subscript'\
      'ion][signup_revenue]=64.00&payload[subscription][delayed_cancel_at]=&pa'\
      'yload[subscription][coupon_code]=&payload[subscription][total_revenue_i'\
      'n_cents]=32000&payload[subscription][product_price_in_cents]=1000&paylo'\
      'ad[subscription][product_version_number]=7&payload[subscription][paymen'\
      't_type]=credit_card&payload[subscription][referral_code]=pggn84&payload'\
      '[subscription][coupon_use_count]=&payload[subscription][coupon_uses_all'\
      'owed]=&payload[subscription][customer][id]=14585695&payload[subscriptio'\
      'n][customer][first_name]=Test&payload[subscription][customer][last_name'\
      ']=Test&payload[subscription][customer][organization]=&payload[subscript'\
      'ion][customer][email]=pookie999%40example.com&payload[subscription][cus'\
      'tomer][created_at]=2016-11-04%2017%3A06%3A42%20-0400&payload[subscripti'\
      'on][customer][updated_at]=2016-11-04%2017%3A06%3A45%20-0400&payload[sub'\
      'scription][customer][reference]=&payload[subscription][customer][addres'\
      's]=&payload[subscription][customer][address_2]=&payload[subscription][c'\
      'ustomer][city]=&payload[subscription][customer][state]=&payload[subscri'\
      'ption][customer][zip]=&payload[subscription][customer][country]=&payloa'\
      'd[subscription][customer][phone]=&payload[subscription][customer][porta'\
      'l_invite_last_sent_at]=2016-11-04%2017%3A06%3A45%20-0400&payload[subscr'\
      'iption][customer][portal_invite_last_accepted_at]=&payload[subscription'\
      '][customer][verified]=false&payload[subscription][customer][portal_cust'\
      'omer_created_at]=2016-11-04%2017%3A06%3A45%20-0400&payload[subscription'\
      '][customer][cc_emails]=&payload[subscription][product][id]=3792003&payl'\
      'oad[subscription][product][name]=%2410%20Basic%20Plan&payload[subscript'\
      'ion][product][handle]=basic&payload[subscription][product][description]'\
      '=lorem%20ipsum&payload[subscription][product][accounting_code]=basic&pa'\
      'yload[subscription][product][request_credit_card]=false&payload[subscri'\
      'ption][product][expiration_interval]=&payload[subscription][product][ex'\
      'piration_interval_unit]=never&payload[subscription][product][created_at'\
      ']=2016-03-24%2013%3A38%3A39%20-0400&payload[subscription][product][upda'\
      'ted_at]=2016-11-03%2013%3A03%3A05%20-0400&payload[subscription][product'\
      '][price_in_cents]=1000&payload[subscription][product][interval]=1&paylo'\
      'ad[subscription][product][interval_unit]=day&payload[subscription][prod'\
      'uct][initial_charge_in_cents]=&payload[subscription][product][trial_pri'\
      'ce_in_cents]=&payload[subscription][product][trial_interval]=&payload[s'\
      'ubscription][product][trial_interval_unit]=month&payload[subscription]['\
      'product][archived_at]=&payload[subscription][product][require_credit_ca'\
      'rd]=false&payload[subscription][product][return_params]=&payload[subscr'\
      'iption][product][taxable]=false&payload[subscription][product][update_r'\
      'eturn_url]=&payload[subscription][product][initial_charge_after_trial]='\
      'false&payload[subscription][product][version_number]=7&payload[subscrip'\
      'tion][product][update_return_params]=&payload[subscription][product][pr'\
      'oduct_family][id]=527890&payload[subscription][product][product_family]'\
      '[name]=Acme%20Projects&payload[subscription][product][product_family][d'\
      'escription]=&payload[subscription][product][product_family][handle]=bil'\
      'ling-plans&payload[subscription][product][product_family][accounting_co'\
      'de]=&payload[subscription][product][public_signup_pages][id]=281054&pay'\
      'load[subscription][product][public_signup_pages][return_url]=http%3A%2F'\
      '%2Fwww.example.com%3Fsuccessfulsignup&payload[subscription][product][pu'\
      'blic_signup_pages][return_params]=&payload[subscription][product][publi'\
      'c_signup_pages][url]=https%3A%2F%2Fgeneral-goods.chargify.com%2Fsubscri'\
      'be%2Fkqvmfrbgd89q%2Fbasic&payload[subscription][product][public_signup_'\
      'pages][id]=281240&payload[subscription][product][public_signup_pages][r'\
      'eturn_url]=&payload[subscription][product][public_signup_pages][return_'\
      'params]=&payload[subscription][product][public_signup_pages][url]=https'\
      '%3A%2F%2Fgeneral-goods.chargify.com%2Fsubscribe%2Fdkffht5dxfd8%2Fbasic&'\
      'payload[subscription][product][public_signup_pages][id]=282694&payload['\
      'subscription][product][public_signup_pages][return_url]=&payload[subscr'\
      'iption][product][public_signup_pages][return_params]=&payload[subscript'\
      'ion][product][public_signup_pages][url]=https%3A%2F%2Fgeneral-goods.cha'\
      'rgify.com%2Fsubscribe%2Fjwffwgdd95s8%2Fbasic&payload[subscription][cred'\
      'it_card][id]=10102821&payload[subscription][credit_card][first_name]=Po'\
      'okie&payload[subscription][credit_card][last_name]=Test&payload[subscri'\
      'ption][credit_card][masked_card_number]=XXXX-XXXX-XXXX-1&payload[subscr'\
      'iption][credit_card][card_type]=bogus&payload[subscription][credit_card'\
      '][expiration_month]=10&payload[subscription][credit_card][expiration_ye'\
      'ar]=2020&payload[subscription][credit_card][customer_id]=14585695&paylo'\
      'ad[subscription][credit_card][current_vault]=bogus&payload[subscription'\
      '][credit_card][vault_token]=1&payload[subscription][credit_card][billin'\
      'g_address]=&payload[subscription][credit_card][billing_city]=&payload[s'\
      'ubscription][credit_card][billing_state]=&payload[subscription][credit_'\
      'card][billing_zip]=&payload[subscription][credit_card][billing_country]'\
      '=&payload[subscription][credit_card][customer_vault_token]=&payload[sub'\
      'scription][credit_card][billing_address_2]=&payload[subscription][credi'\
      't_card][payment_type]=credit_card&payload[subscription][credit_card][si'\
      'te_gateway_setting_id]=&payload[subscription][credit_card][gateway_hand'\
      'le]=&payload[transaction][id]=161537369&payload[transaction][subscripti'\
      'on_id]=15100141&payload[transaction][type]=Payment&payload[transaction]'\
      '[kind]=&payload[transaction][transaction_type]=payment&payload[transact'\
      'ion][success]=true&payload[transaction][amount_in_cents]=6400&payload[t'\
      'ransaction][memo]=Pookie%20Test%20-%20%2410%20Basic%20Plan%3A%20Renewal'\
      '%20payment&payload[transaction][created_at]=2016-11-08%2016%3A22%3A20%2'\
      '0-0500&payload[transaction][starting_balance_in_cents]=6400&payload[tra'\
      'nsaction][ending_balance_in_cents]=0&payload[transaction][gateway_used]'\
      '=bogus&payload[transaction][gateway_transaction_id]=53433&payload[trans'\
      'action][gateway_response_code]=&payload[transaction][gateway_order_id]='\
      '&payload[transaction][payment_id]=&payload[transaction][product_id]=379'\
      '2003&payload[transaction][tax_id]=&payload[transaction][component_id]=&'\
      'payload[transaction][statement_id]=80168049&payload[transaction][custom'\
      'er_id]=14585695&payload[transaction][card_number]=XXXX-XXXX-XXXX-1&payl'\
      'oad[transaction][card_expiration]=10%2F2020&payload[transaction][card_t'\
      'ype]=bogus&payload[transaction][refunded_amount_in_cents]=0&payload[tra'\
      'nsaction][invoice_id]=&payload[event_id]=347299364","signature":"fbcf2f'\
      '6be579f9658cff90c4373e0ca2","signature_hmac_sha_256":"db96654f5456c5460'\
      '062feb944ac8bb1418f9d181ae04a8ed982fe9ffdca8de1"}}]'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # This method allows you to enable webhooks via API for your site
  def test_enable_webhooks
    # Parameters for the API call
    body = EnableWebhooksRequest.from_hash(APIHelper.json_deserialize(
      '{"webhooks_enabled":true}', false))

    # Perform the API call through the SDK function
    result = @controller.enable_webhooks(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"webhooks_enabled":true}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # Posting to the replay endpoint does not immediately resend the webhooks. They are added to a queue and will be sent as soon as possible, depending on available system resources.
  #
  #You may submit an array of up to 1000 webhook IDs to replay in the request.
  def test_replay_webhooks
    # Parameters for the API call
    body = ReplayWebhooksRequest.from_hash(APIHelper.json_deserialize(
      '{"ids":[123456789,123456788]}', false))

    # Perform the API call through the SDK function
    result = @controller.replay_webhooks(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"status":"ok"}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # The Chargify API allows you to create an endpoint and assign a list of webhooks subscriptions (events) to it.
  #
  #You can check available events here.
  #[Event keys](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405357509645-Webhooks-Reference#example-payloads)
  def test_create_endpoint
    # Parameters for the API call
    body = UpdateEndpointRequest.from_hash(APIHelper.json_deserialize(
      '{"endpoint":{"url":"https://your.site/webhooks","webhook_subscriptions"'\
      ':["payment_success","payment_failure"]}}', false))

    # Perform the API call through the SDK function
    result = @controller.create_endpoint(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"endpoint":{"id":1,"url":"https://your.site/webhooks","site_id":1,"sta'\
      'tus":"enabled","webhook_subscriptions":["payment_success","payment_fail'\
      'ure"]}}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # This method returns created endpoints for site.
  def test_list_endpoints

    # Perform the API call through the SDK function
    result = @controller.list_endpoints()

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '[{"id":11,"url":"https://foobar.com/webhooks","site_id":1,"status":"ena'\
      'bled","webhook_subscriptions":["payment_success","payment_failure"]},{"'\
      'id":12,"url":"https:/example.com/webhooks","site_id":1,"status":"enable'\
      'd","webhook_subscriptions":["payment_success","payment_failure","refund'\
      '_failure"]}]'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

end