# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # ComponentPricePoint Model.
  class ComponentPricePoint < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # Price point type. We expose the following types:
    # 1. **default**: a price point that is marked as a default price for a
    # certain product.
    # 2. **custom**: a custom price point.
    # 3. **catalog**: a price point that is **not** marked as a default price
    # for a certain product and is **not** a custom one.
    # @return [PricePointType]
    attr_accessor :type

    # Note: Refer to type attribute instead
    # @return [TrueClass | FalseClass]
    attr_accessor :default

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :name

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :pricing_scheme

    # Note: Refer to type attribute instead
    # @return [Integer]
    attr_accessor :component_id

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :handle

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :archived_at

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :created_at

    # Note: Refer to type attribute instead
    # @return [String]
    attr_accessor :updated_at

    # Note: Refer to type attribute instead
    # @return [Array[ComponentPricePointPrice]]
    attr_accessor :prices

    # Whether to use the site level exchange rate or define your own prices for
    # each currency if you have multiple currencies defined on the site.
    # @return [TrueClass | FalseClass]
    attr_accessor :use_site_exchange_rate

    # (only used for Custom Pricing - ie. when the price point's type is
    # `custom`) The id of the subscription that the custom price point is for.
    # @return [Integer]
    attr_accessor :subscription_id

    # (only used for Custom Pricing - ie. when the price point's type is
    # `custom`) The id of the subscription that the custom price point is for.
    # @return [TrueClass | FalseClass]
    attr_accessor :tax_included

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash['default'] = 'default'
      @_hash['name'] = 'name'
      @_hash['pricing_scheme'] = 'pricing_scheme'
      @_hash['component_id'] = 'component_id'
      @_hash['handle'] = 'handle'
      @_hash['archived_at'] = 'archived_at'
      @_hash['created_at'] = 'created_at'
      @_hash['updated_at'] = 'updated_at'
      @_hash['prices'] = 'prices'
      @_hash['use_site_exchange_rate'] = 'use_site_exchange_rate'
      @_hash['subscription_id'] = 'subscription_id'
      @_hash['tax_included'] = 'tax_included'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        type
        default
        name
        pricing_scheme
        component_id
        handle
        archived_at
        created_at
        updated_at
        prices
        use_site_exchange_rate
        subscription_id
        tax_included
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        archived_at
      ]
    end

    def initialize(id = SKIP,
                   type = SKIP,
                   default = SKIP,
                   name = SKIP,
                   pricing_scheme = SKIP,
                   component_id = SKIP,
                   handle = SKIP,
                   archived_at = SKIP,
                   created_at = SKIP,
                   updated_at = SKIP,
                   prices = SKIP,
                   use_site_exchange_rate = true,
                   subscription_id = SKIP,
                   tax_included = SKIP)
      @id = id unless id == SKIP
      @type = type unless type == SKIP
      @default = default unless default == SKIP
      @name = name unless name == SKIP
      @pricing_scheme = pricing_scheme unless pricing_scheme == SKIP
      @component_id = component_id unless component_id == SKIP
      @handle = handle unless handle == SKIP
      @archived_at = archived_at unless archived_at == SKIP
      @created_at = created_at unless created_at == SKIP
      @updated_at = updated_at unless updated_at == SKIP
      @prices = prices unless prices == SKIP
      @use_site_exchange_rate = use_site_exchange_rate unless use_site_exchange_rate == SKIP
      @subscription_id = subscription_id unless subscription_id == SKIP
      @tax_included = tax_included unless tax_included == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      default = hash.key?('default') ? hash['default'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      pricing_scheme =
        hash.key?('pricing_scheme') ? hash['pricing_scheme'] : SKIP
      component_id = hash.key?('component_id') ? hash['component_id'] : SKIP
      handle = hash.key?('handle') ? hash['handle'] : SKIP
      archived_at = hash.key?('archived_at') ? hash['archived_at'] : SKIP
      created_at = hash.key?('created_at') ? hash['created_at'] : SKIP
      updated_at = hash.key?('updated_at') ? hash['updated_at'] : SKIP
      # Parameter is an array, so we need to iterate through it
      prices = nil
      unless hash['prices'].nil?
        prices = []
        hash['prices'].each do |structure|
          prices << (ComponentPricePointPrice.from_hash(structure) if structure)
        end
      end

      prices = SKIP unless hash.key?('prices')
      use_site_exchange_rate = hash['use_site_exchange_rate'] ||= true
      subscription_id =
        hash.key?('subscription_id') ? hash['subscription_id'] : SKIP
      tax_included = hash.key?('tax_included') ? hash['tax_included'] : SKIP

      # Create object from extracted values.
      ComponentPricePoint.new(id,
                              type,
                              default,
                              name,
                              pricing_scheme,
                              component_id,
                              handle,
                              archived_at,
                              created_at,
                              updated_at,
                              prices,
                              use_site_exchange_rate,
                              subscription_id,
                              tax_included)
    end
  end
end
