# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # CreateInvoicePaymentRequest Model.
  class CreateInvoicePaymentRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [CreateInvoicePayment]
    attr_accessor :payment

    # The type of payment to be applied to an Invoice. Defaults to external.
    # @return [InvoicePaymentType]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment'] = 'payment'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment:, type: SKIP, additional_properties: {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @payment = payment
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment = CreateInvoicePayment.from_hash(hash['payment']) if hash['payment']
      type = hash.key?('type') ? hash['type'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      CreateInvoicePaymentRequest.new(payment: payment,
                                      type: type,
                                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} payment: #{@payment}, type: #{@type}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} payment: #{@payment.inspect}, type: #{@type.inspect},"\
      " additional_properties: #{get_additional_properties}>"
    end
  end
end
