# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # CustomerChange Model.
  class CustomerChange < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [CustomerPayerChange]
    attr_accessor :payer

    # TODO: Write general description for this method
    # @return [AddressChange]
    attr_accessor :shipping_address

    # TODO: Write general description for this method
    # @return [AddressChange]
    attr_accessor :billing_address

    # TODO: Write general description for this method
    # @return [CustomerCustomFieldsChange]
    attr_accessor :custom_fields

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payer'] = 'payer'
      @_hash['shipping_address'] = 'shipping_address'
      @_hash['billing_address'] = 'billing_address'
      @_hash['custom_fields'] = 'custom_fields'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payer
        shipping_address
        billing_address
        custom_fields
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        payer
        shipping_address
        billing_address
        custom_fields
      ]
    end

    def initialize(payer = SKIP,
                   shipping_address = SKIP,
                   billing_address = SKIP,
                   custom_fields = SKIP,
                   additional_properties = {})
      @payer = payer unless payer == SKIP
      @shipping_address = shipping_address unless shipping_address == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @custom_fields = custom_fields unless custom_fields == SKIP

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payer = hash.key?('payer') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:CustomerChangePayer), hash['payer']
      ) : SKIP
      shipping_address = hash.key?('shipping_address') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:CustomerChangeShippingAddress), hash['shipping_address']
      ) : SKIP
      billing_address = hash.key?('billing_address') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:CustomerChangeBillingAddress), hash['billing_address']
      ) : SKIP
      custom_fields = hash.key?('custom_fields') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:CustomerChangeCustomFields), hash['custom_fields']
      ) : SKIP

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      CustomerChange.new(payer,
                         shipping_address,
                         billing_address,
                         custom_fields,
                         hash)
    end

    # Validates an instance of the object from a given value.
    # @param [CustomerChange | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end
  end
end
