# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # List Subscription Components Sort.
  class ListSubscriptionComponentsSort
    LIST_SUBSCRIPTION_COMPONENTS_SORT = [
      # TODO: Write general description for ID
      ID = 'id'.freeze,

      # TODO: Write general description for UPDATED_AT
      UPDATED_AT = 'updated_at'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      LIST_SUBSCRIPTION_COMPONENTS_SORT.include?(value)
    end
  end
end
