# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # Recurring Scheme.
  class RecurringScheme
    RECURRING_SCHEME = [
      # TODO: Write general description for DO_NOT_RECUR
      DO_NOT_RECUR = 'do_not_recur'.freeze,

      # TODO: Write general description for RECUR_INDEFINITELY
      RECUR_INDEFINITELY = 'recur_indefinitely'.freeze,

      # TODO: Write general description for RECUR_WITH_DURATION
      RECUR_WITH_DURATION = 'recur_with_duration'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      RECURRING_SCHEME.include?(value)
    end
  end
end
