# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # ReferralValidationResponse Model.
  class ReferralValidationResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ReferralCode]
    attr_accessor :referral_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['referral_code'] = 'referral_code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        referral_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(referral_code = SKIP)
      @referral_code = referral_code unless referral_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      referral_code = ReferralCode.from_hash(hash['referral_code']) if hash['referral_code']

      # Create object from extracted values.
      ReferralValidationResponse.new(referral_code)
    end
  end
end
