# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # RefundPrepaymentAggregatedError Model.
  class RefundPrepaymentAggregatedError < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [PrepaymentAggregatedError]
    attr_accessor :refund

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['refund'] = 'refund'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        refund
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(refund = SKIP)
      @refund = refund unless refund == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      refund = PrepaymentAggregatedError.from_hash(hash['refund']) if hash['refund']

      # Create object from extracted values.
      RefundPrepaymentAggregatedError.new(refund)
    end
  end
end
