# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # Subscription Groups List Include.
  class SubscriptionGroupsListInclude
    SUBSCRIPTION_GROUPS_LIST_INCLUDE = [
      # TODO: Write general description for ACCOUNT_BALANCES
      ACCOUNT_BALANCES = 'account_balances'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SUBSCRIPTION_GROUPS_LIST_INCLUDE.include?(value)
    end
  end
end
