# advanced_billing
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module AdvancedBilling
  # SubscriptionComponentResponse Model.
  class SubscriptionComponentResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [SubscriptionComponent]
    attr_accessor :component

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['component'] = 'component'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        component
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(component = SKIP)
      @component = component unless component == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      component = SubscriptionComponent.from_hash(hash['component']) if hash['component']

      # Create object from extracted values.
      SubscriptionComponentResponse.new(component)
    end
  end
end
