name: Build & run tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Run tests
        working-directory: ./spec
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          bundle install
          bundle exec rspec *_spec.rb
